"""
HexaSentinel — Report Generation Endpoints
CERT-In format incident reports and ISP NOC notifications,
generated by Llama 3.2 3B on the Hexagon NPU.
"""

import datetime
from fastapi import APIRouter
from pydantic import BaseModel
from ..agents.orchestrator import orchestrator

router = APIRouter(prefix="/api/reports")


class CERTInRequest(BaseModel):
    incident: dict = {}
    analysis: str  = ""


class ISPRequest(BaseModel):
    incident: dict = {}
    analysis: str  = ""


@router.post("/certin")
async def certin_report(body: CERTInRequest):
    inc_id  = f"CERT-IN-NW-{datetime.datetime.now().strftime('%Y%m%d-%H%M%S')}"
    text    = orchestrator.generate_certin_report(body.incident, body.analysis)
    return {
        "id":          inc_id,
        "text":        text,
        "generatedAt": datetime.datetime.utcnow().isoformat() + "Z",
        "generatedBy": "Llama 3.2 3B Instruct — Qualcomm AI Hub — Hexagon NPU",
    }


@router.post("/isp")
async def isp_notification(body: ISPRequest):
    text = orchestrator.generate_isp_notification(body.incident)
    return {
        "text":        text,
        "generatedAt": datetime.datetime.utcnow().isoformat() + "Z",
        "generatedBy": "Llama 3.2 3B Instruct — Qualcomm AI Hub — Hexagon NPU",
    }
